//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseColors
    {
        public BaseColors()
        {
            this.Templates = new HashSet<Templates>();
        }
    
        public int BaseColorID { get; set; }
        public string Color { get; set; }
        public Nullable<int> type { get; set; }
        public string RGB { get; set; }
        public string HEX { get; set; }
        public string CMYK { get; set; }
    
        public virtual ICollection<Templates> Templates { get; set; }
    }
}
