//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryRegions
    {
        public CategoryRegions()
        {
            this.tbl_ProductCategory = new HashSet<tbl_ProductCategory>();
        }
    
        public int RegionID { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
    
        public virtual ICollection<tbl_ProductCategory> tbl_ProductCategory { get; set; }
    }
}
