//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryLayouts
    {
        public CategoryLayouts()
        {
            this.LayoutAttributes = new HashSet<LayoutAttributes>();
        }
    
        public int LayoutID { get; set; }
        public string Title { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<int> Orientation { get; set; }
        public Nullable<int> ImageLogoType { get; set; }
    
        public virtual tbl_ProductCategory tbl_ProductCategory { get; set; }
        public virtual ICollection<LayoutAttributes> LayoutAttributes { get; set; }
    }
}
