//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayoutAttributes
    {
        public int AttId { get; set; }
        public Nullable<int> LayoutID { get; set; }
        public string maxWidth { get; set; }
        public string maxHeight { get; set; }
        public Nullable<decimal> fontSize { get; set; }
        public string textAlign { get; set; }
        public string fontWeight { get; set; }
        public Nullable<decimal> topPos { get; set; }
        public Nullable<decimal> LeftPos { get; set; }
        public string FeildName { get; set; }
    
        public virtual CategoryLayouts CategoryLayouts { get; set; }
    }
}
