//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    
    public partial class QuickText
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string CompanyMessage { get; set; }
        public string LogoPath { get; set; }
        public int CustomerID { get; set; }
        public int ContactID { get; set; }
        public string FacebookID { get; set; }
        public string TwitterID { get; set; }
        public string LinkedInID { get; set; }
        public string OtherId { get; set; }
        public string MobileNumber { get; set; }
    }
}
