//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public Tags()
        {
            this.TemplateThemeTags = new HashSet<TemplateThemeTags>();
            this.TemplateIndustryTags = new HashSet<TemplateIndustryTags>();
        }
    
        public int TagID { get; set; }
        public string TagName { get; set; }
        public string TagSlug { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<TemplateThemeTags> TemplateThemeTags { get; set; }
        public virtual ICollection<TemplateIndustryTags> TemplateIndustryTags { get; set; }
    }
}
