//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    [Serializable]
    [KnownType(typeof(MatchingSetCategories))]
    [KnownType(typeof(tbl_ProductCategoryFoldLines))]
    [KnownType(typeof(CategoryLayouts))]
    [KnownType(typeof(Templates))]
    [KnownType(typeof(CategoryRegions))]
    [KnownType(typeof(CategoryTypes))]

    public partial class tbl_ProductCategory
    {
        public tbl_ProductCategory()
        {
            this.MatchingSetCategories = new HashSet<MatchingSetCategories>();
            this.tbl_ProductCategory1 = new HashSet<tbl_ProductCategory>();
            this.tbl_ProductCategoryFoldLines = new HashSet<tbl_ProductCategoryFoldLines>();
            this.CategoryLayouts = new HashSet<CategoryLayouts>();
            this.Templates = new HashSet<Templates>();
        }
    
        public int ProductCategoryID { get; set; }
        public string CategoryName { get; set; }
        public string ContentType { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public int LockedBy { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public int DisplayOrder { get; set; }
        public string ImagePath { get; set; }
        public string ThumbnailPath { get; set; }
        public Nullable<bool> ApplySizeRestrictions { get; set; }
        public Nullable<double> WidthRestriction { get; set; }
        public Nullable<double> HeightRestriction { get; set; }
        public Nullable<bool> ApplyFoldLines { get; set; }
        public Nullable<int> CatagoryTypeID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<decimal> ZoomFactor { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<decimal> ScaleFactor { get; set; }
        public Nullable<bool> displayOnClydy { get; set; }
        public string userFriendlyName { get; set; }
        public string categoryDescription { get; set; }
    
        public virtual CategoryRegions CategoryRegions { get; set; }
        public virtual CategoryTypes CategoryTypes { get; set; }
        public virtual ICollection<MatchingSetCategories> MatchingSetCategories { get; set; }
        public virtual ICollection<tbl_ProductCategory> tbl_ProductCategory1 { get; set; }
        public virtual tbl_ProductCategory tbl_ProductCategory2 { get; set; }
        public virtual ICollection<tbl_ProductCategoryFoldLines> tbl_ProductCategoryFoldLines { get; set; }
        public virtual ICollection<CategoryLayouts> CategoryLayouts { get; set; }
        public virtual ICollection<Templates> Templates { get; set; }
    }
}
