//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProductCategoryFoldLines
    {
        public int FoldLineID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<bool> FoldLineOrientation { get; set; }
        public Nullable<double> FoldLineOffsetFromOrigin { get; set; }
    
        public virtual tbl_ProductCategory tbl_ProductCategory { get; set; }
    }
}
