//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class TemplatePages
    {
        public TemplatePages()
        {
            this.TemplateObjects = new HashSet<TemplateObjects>();
        }
    
        public int ProductPageID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<int> PageType { get; set; }
        public Nullable<int> Orientation { get; set; }
        public Nullable<int> BackGroundType { get; set; }
        public string BackgroundFileName { get; set; }
        public Nullable<int> ColorC { get; set; }
        public Nullable<int> ColorM { get; set; }
        public Nullable<int> ColorY { get; set; }
        public string PageName { get; set; }
        public Nullable<int> ColorK { get; set; }
        public Nullable<bool> IsPrintable { get; set; }
        public Nullable<bool> hasOverlayObjects { get; set; }
    
        public virtual ICollection<TemplateObjects> TemplateObjects { get; set; }
        public virtual Templates Templates { get; set; }
    }
}
