//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateBackgroundImages
    {
        public TemplateBackgroundImages()
        {
            this.ImagePermissions = new HashSet<ImagePermissions>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ImageName { get; set; }
        public string Name { get; set; }
        public Nullable<bool> flgPhotobook { get; set; }
        public Nullable<bool> flgCover { get; set; }
        public string BackgroundImageAbsolutePath { get; set; }
        public string BackgroundImageRelativePath { get; set; }
        public Nullable<int> ImageType { get; set; }
        public Nullable<int> ImageWidth { get; set; }
        public Nullable<int> ImageHeight { get; set; }
        public string ImageTitle { get; set; }
        public string ImageDescription { get; set; }
        public string ImageKeywords { get; set; }
        public Nullable<int> UploadedFrom { get; set; }
        public Nullable<int> ContactCompanyID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<bool> hasClippingPath { get; set; }
        public string clippingFileName { get; set; }
    
        public virtual ICollection<ImagePermissions> ImagePermissions { get; set; }
        public virtual Templates Templates { get; set; }
    }
}
