//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
  [DataContract]
    public partial class TemplatePagesModel
    {
        public TemplatePagesModel()
        {
            
        }
      [DataMember]
        public int ProductPageID { get; set; }
      [DataMember]
      public Nullable<int> ProductID { get; set; }
      [DataMember]
      public Nullable<int> PageNo { get; set; }
      [DataMember]
      public Nullable<int> PageType { get; set; }
      [DataMember]
      public Nullable<int> Orientation { get; set; }
      [DataMember]
      public Nullable<int> BackGroundType { get; set; }
      [DataMember]
      public string BackgroundFileName { get; set; }
      [DataMember]
      public Nullable<int> ColorC { get; set; }
      [DataMember]
      public Nullable<int> ColorM { get; set; }
      [DataMember]
      public Nullable<int> ColorY { get; set; }
      [DataMember]
      public string PageName { get; set; }
      [DataMember]
      public Nullable<int> ColorK { get; set; }
      [DataMember]
      public Nullable<bool> IsPrintable { get; set; }
      [DataMember]
        public Nullable<bool> hasOverlayObjects { get; set; }
    }
}
