//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Templates
    {
        public Templates()
        {
            this.TemplateColorStyles = new HashSet<TemplateColorStyles>();
            this.TemplateFonts = new HashSet<TemplateFonts>();
            this.TemplateFontStyles = new HashSet<TemplateFontStyles>();
            this.TemplateIndustryTags = new HashSet<TemplateIndustryTags>();
            this.TemplateKeywords = new HashSet<TemplateKeywords>();
            this.TemplateThemeTags = new HashSet<TemplateThemeTags>();
            this.TemplateSide2Templates = new HashSet<TemplateSide2Templates>();
            this.TemplateSide2Templates1 = new HashSet<TemplateSide2Templates>();
            this.TemplateBackgroundImages = new HashSet<TemplateBackgroundImages>();
            this.TemplatePages = new HashSet<TemplatePages>();
        }
    
        public int ProductID { get; set; }
        public string Code { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public string LowResPDFTemplates { get; set; }
        public string BackgroundArtwork { get; set; }
        public string Side2LowResPDFTemplates { get; set; }
        public string Side2BackgroundArtwork { get; set; }
        public string Thumbnail { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<int> PTempId { get; set; }
        public bool IsDoubleSide { get; set; }
        public bool IsUsePDFFile { get; set; }
        public Nullable<double> PDFTemplateWidth { get; set; }
        public Nullable<double> PDFTemplateHeight { get; set; }
        public Nullable<bool> IsUseBackGroundColor { get; set; }
        public Nullable<int> BgR { get; set; }
        public Nullable<int> BgG { get; set; }
        public Nullable<int> BgB { get; set; }
        public Nullable<bool> IsUseSide2BackGroundColor { get; set; }
        public Nullable<int> Side2BgR { get; set; }
        public Nullable<int> Side2BgG { get; set; }
        public Nullable<int> Side2BgB { get; set; }
        public Nullable<double> CuttingMargin { get; set; }
        public Nullable<int> MultiPageCount { get; set; }
        public Nullable<int> Orientation { get; set; }
        public string MatchingSetTheme { get; set; }
        public Nullable<int> BaseColorID { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public string SubmittedByName { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ApprovedByName { get; set; }
        public Nullable<int> UserRating { get; set; }
        public Nullable<int> UsedCount { get; set; }
        public Nullable<int> MPCRating { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string TempString { get; set; }
        public Nullable<int> MatchingSetID { get; set; }
        public string SLThumbnail { get; set; }
        public string FullView { get; set; }
        public string SuperView { get; set; }
        public string ColorHex { get; set; }
        public Nullable<int> TemplateOwner { get; set; }
        public string TemplateOwnerName { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsCorporateEditable { get; set; }
        public Nullable<int> TemplateType { get; set; }
        public Nullable<bool> isWatermarkText { get; set; }
        public Nullable<bool> isSpotTemplate { get; set; }
        public Nullable<bool> isCreatedManual { get; set; }
        public Nullable<bool> isEditorChoice { get; set; }
        public Nullable<decimal> ScaleFactor { get; set; }
    
        public virtual BaseColors BaseColors { get; set; }
        public virtual tbl_ProductCategory tbl_ProductCategory { get; set; }
        public virtual ICollection<TemplateColorStyles> TemplateColorStyles { get; set; }
        public virtual ICollection<TemplateFonts> TemplateFonts { get; set; }
        public virtual ICollection<TemplateFontStyles> TemplateFontStyles { get; set; }
        public virtual ICollection<TemplateIndustryTags> TemplateIndustryTags { get; set; }
        public virtual ICollection<TemplateKeywords> TemplateKeywords { get; set; }
        public virtual ICollection<TemplateThemeTags> TemplateThemeTags { get; set; }
        public virtual ICollection<TemplateSide2Templates> TemplateSide2Templates { get; set; }
        public virtual ICollection<TemplateSide2Templates> TemplateSide2Templates1 { get; set; }
        public virtual ICollection<TemplateBackgroundImages> TemplateBackgroundImages { get; set; }
        public virtual ICollection<TemplatePages> TemplatePages { get; set; }
    }
}
