//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    
    public partial class TemplateFontsModel
    {
        [DataMember]
        public int ProductFontId { get; set; }
        [DataMember]
        public Nullable<int> ProductId { get; set; }
        [DataMember]
        public string FontName { get; set; }
        [DataMember]
        public string FontDisplayName { get; set; }
        [DataMember]
        public string FontFile { get; set; }
        [DataMember]
        public Nullable<int> DisplayIndex { get; set; }
        [DataMember]
        public bool IsPrivateFont { get; set; }
        [DataMember]
        public Nullable<bool> IsEnable { get; set; }
        [DataMember]
        public byte[] FontBytes { get; set; }
        [DataMember]
        public Nullable<int> CustomerID { get; set; }
        [DataMember]
        public string FontPath { get; set; }

       
    }
}
