//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class TemplateObjects
    {
        public int ObjectID { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<double> PositionX { get; set; }
        public Nullable<double> PositionY { get; set; }
        public Nullable<double> MaxHeight { get; set; }
        public Nullable<double> MaxWidth { get; set; }
        public Nullable<double> MaxCharacters { get; set; }
        public Nullable<double> RotationAngle { get; set; }
        public Nullable<bool> IsFontCustom { get; set; }
        public Nullable<bool> IsFontNamePrivate { get; set; }
        public string FontName { get; set; }
        public Nullable<double> FontSize { get; set; }
        public Nullable<int> FontStyleID { get; set; }
        public Nullable<bool> IsBold { get; set; }
        public Nullable<bool> IsItalic { get; set; }
        public Nullable<int> Allignment { get; set; }
        public Nullable<int> VAllignment { get; set; }
        public Nullable<double> Indent { get; set; }
        public Nullable<bool> IsUnderlinedText { get; set; }
        public Nullable<int> ColorType { get; set; }
        public Nullable<int> ColorStyleID { get; set; }
        public Nullable<int> PalleteID { get; set; }
        public string ColorName { get; set; }
        public Nullable<int> ColorC { get; set; }
        public Nullable<int> ColorM { get; set; }
        public Nullable<int> ColorY { get; set; }
        public Nullable<int> ColorK { get; set; }
        public Nullable<int> Tint { get; set; }
        public Nullable<bool> IsSpotColor { get; set; }
        public string SpotColorName { get; set; }
        public string ContentString { get; set; }
        public Nullable<int> ContentCaseType { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> DisplayOrderPdf { get; set; }
        public Nullable<int> DisplayOrderTxtControl { get; set; }
        public Nullable<bool> IsRequireNumericValue { get; set; }
        public Nullable<int> RColor { get; set; }
        public Nullable<int> GColor { get; set; }
        public Nullable<int> BColor { get; set; }
        public Nullable<bool> isSide2Object { get; set; }
        public Nullable<double> LineSpacing { get; set; }
        public Nullable<int> ProductPageId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<double> CircleRadiusX { get; set; }
        public Nullable<double> Opacity { get; set; }
        public Nullable<bool> IsNewLine { get; set; }
        public string TCtlName { get; set; }
        public string ExField1 { get; set; }
        public string ExField2 { get; set; }
        public Nullable<bool> IsPositionLocked { get; set; }
        public string ColorHex { get; set; }
        public Nullable<double> CircleRadiusY { get; set; }
        public Nullable<bool> IsTextEditable { get; set; }
        public Nullable<int> QuickTextOrder { get; set; }
        public Nullable<bool> IsQuickText { get; set; }
        public Nullable<double> CharSpacing { get; set; }
        public string watermarkText { get; set; }
        public string textStyles { get; set; }
        public Nullable<bool> AutoShrinkText { get; set; }
        public Nullable<bool> IsOverlayObject { get; set; }
        public string ClippedInfo { get; set; }
        public Nullable<int> textCase { get; set; }
        public Nullable<bool> hasClippingPath { get; set; }
    
        public virtual TemplatePages TemplatePages { get; set; }
    }
}
