//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
using System.Runtime.Serialization;
    [DataContract]
    public partial class TemplateBackgroundImagesModel
    {
        public TemplateBackgroundImagesModel()
        {
            
        }
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public Nullable<int> ProductID { get; set; }
        [DataMember]
        public string ImageName { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public Nullable<bool> flgPhotobook { get; set; }
        [DataMember]
        public Nullable<bool> flgCover { get; set; }
        [DataMember]
        public string BackgroundImageAbsolutePath { get; set; }
        [DataMember]
        public string BackgroundImageRelativePath { get; set; }
        [DataMember]
        public Nullable<int> ImageType { get; set; }
        [DataMember]
        public Nullable<int> ImageWidth { get; set; }
        [DataMember]
        public Nullable<int> ImageHeight { get; set; }
        [DataMember]
        public string ImageTitle { get; set; }
        [DataMember]
        public string ImageDescription { get; set; }
        [DataMember]
        public string ImageKeywords { get; set; }
        [DataMember]
        public Nullable<int> UploadedFrom { get; set; }
        [DataMember]
        public Nullable<int> ContactCompanyID { get; set; }
        [DataMember]
        public Nullable<int> ContactID { get; set; }
        [DataMember]
        public Nullable<bool> hasClippingPath { get; set; }
        [DataMember]
        public string clippingFileName { get; set; }

        
    }
}
