//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateIndustryTags
    {
        public int TemplateIndustryTagID { get; set; }
        public Nullable<int> TagID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Tags Tags { get; set; }
        public virtual Templates Templates { get; set; }
    }
}
