//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProductCategoriesLeafNodes
    {
        public int ProductCategoryID { get; set; }
        public int ParentCategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<int> CatagoryTypeID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<decimal> ZoomFactor { get; set; }
        public Nullable<decimal> ScaleFactor { get; set; }
    }
}
