//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateDesignerModelV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_WebStore_MatchingSets
    {
        public int ProductID { get; set; }
        public int ProductCategoryID { get; set; }
        public string Code { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Thumbnail { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<int> PTempId { get; set; }
        public bool IsDoubleSide { get; set; }
        public Nullable<bool> IsUseBackGroundColor { get; set; }
        public Nullable<int> MultiPageCount { get; set; }
        public Nullable<int> Orientation { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> MatchingSetID { get; set; }
        public string SLThumbnail { get; set; }
        public string FullView { get; set; }
        public string SuperView { get; set; }
        public Nullable<int> BaseColorID { get; set; }
        public Nullable<bool> isEditorChoice { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> SubmittedBy { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<int> TemplateOwner { get; set; }
        public int DisplayOrder { get; set; }
    }
}
