//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace TemplateDesignerModelTypes
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MatchingSets))]
    [KnownType(typeof(tbl_ProductCategory))]
    public partial class MatchingSetCategories: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _iD;
    
        [DataMember]
        public Nullable<int> MatchingSetID
        {
            get { return _matchingSetID; }
            set
            {
                if (_matchingSetID != value)
                {
                    ChangeTracker.RecordOriginalValue("MatchingSetID", _matchingSetID);
                    if (!IsDeserializing)
                    {
                        if (MatchingSets != null && MatchingSets.MatchingSetID != value)
                        {
                            MatchingSets = null;
                        }
                    }
                    _matchingSetID = value;
                    OnPropertyChanged("MatchingSetID");
                }
            }
        }
        private Nullable<int> _matchingSetID;
    
        [DataMember]
        public Nullable<int> ProductCategoryID
        {
            get { return _productCategoryID; }
            set
            {
                if (_productCategoryID != value)
                {
                    ChangeTracker.RecordOriginalValue("ProductCategoryID", _productCategoryID);
                    if (!IsDeserializing)
                    {
                        if (tbl_ProductCategory != null && tbl_ProductCategory.ProductCategoryID != value)
                        {
                            tbl_ProductCategory = null;
                        }
                    }
                    _productCategoryID = value;
                    OnPropertyChanged("ProductCategoryID");
                }
            }
        }
        private Nullable<int> _productCategoryID;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public MatchingSets MatchingSets
        {
            get { return _matchingSets; }
            set
            {
                if (!ReferenceEquals(_matchingSets, value))
                {
                    var previousValue = _matchingSets;
                    _matchingSets = value;
                    FixupMatchingSets(previousValue);
                    OnNavigationPropertyChanged("MatchingSets");
                }
            }
        }
        private MatchingSets _matchingSets;
    
        [DataMember]
        public tbl_ProductCategory tbl_ProductCategory
        {
            get { return _tbl_ProductCategory; }
            set
            {
                if (!ReferenceEquals(_tbl_ProductCategory, value))
                {
                    var previousValue = _tbl_ProductCategory;
                    _tbl_ProductCategory = value;
                    Fixuptbl_ProductCategory(previousValue);
                    OnNavigationPropertyChanged("tbl_ProductCategory");
                }
            }
        }
        private tbl_ProductCategory _tbl_ProductCategory;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            MatchingSets = null;
            tbl_ProductCategory = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupMatchingSets(MatchingSets previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.MatchingSetCategories.Contains(this))
            {
                previousValue.MatchingSetCategories.Remove(this);
            }
    
            if (MatchingSets != null)
            {
                if (!MatchingSets.MatchingSetCategories.Contains(this))
                {
                    MatchingSets.MatchingSetCategories.Add(this);
                }
    
                MatchingSetID = MatchingSets.MatchingSetID;
            }
            else if (!skipKeys)
            {
                MatchingSetID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("MatchingSets")
                    && (ChangeTracker.OriginalValues["MatchingSets"] == MatchingSets))
                {
                    ChangeTracker.OriginalValues.Remove("MatchingSets");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("MatchingSets", previousValue);
                }
                if (MatchingSets != null && !MatchingSets.ChangeTracker.ChangeTrackingEnabled)
                {
                    MatchingSets.StartTracking();
                }
            }
        }
    
        private void Fixuptbl_ProductCategory(tbl_ProductCategory previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.MatchingSetCategories.Contains(this))
            {
                previousValue.MatchingSetCategories.Remove(this);
            }
    
            if (tbl_ProductCategory != null)
            {
                if (!tbl_ProductCategory.MatchingSetCategories.Contains(this))
                {
                    tbl_ProductCategory.MatchingSetCategories.Add(this);
                }
    
                ProductCategoryID = tbl_ProductCategory.ProductCategoryID;
            }
            else if (!skipKeys)
            {
                ProductCategoryID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("tbl_ProductCategory")
                    && (ChangeTracker.OriginalValues["tbl_ProductCategory"] == tbl_ProductCategory))
                {
                    ChangeTracker.OriginalValues.Remove("tbl_ProductCategory");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("tbl_ProductCategory", previousValue);
                }
                if (tbl_ProductCategory != null && !tbl_ProductCategory.ChangeTracker.ChangeTrackingEnabled)
                {
                    tbl_ProductCategory.StartTracking();
                }
            }
        }

        #endregion
    }
}
