//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace TemplateDesignerModelTypes
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Tags))]
    [KnownType(typeof(Templates))]
    public partial class TemplateThemeTags: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int TemplateThemeTagID
        {
            get { return _templateThemeTagID; }
            set
            {
                if (_templateThemeTagID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'TemplateThemeTagID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _templateThemeTagID = value;
                    OnPropertyChanged("TemplateThemeTagID");
                }
            }
        }
        private int _templateThemeTagID;
    
        [DataMember]
        public Nullable<int> TagID
        {
            get { return _tagID; }
            set
            {
                if (_tagID != value)
                {
                    ChangeTracker.RecordOriginalValue("TagID", _tagID);
                    if (!IsDeserializing)
                    {
                        if (Tags != null && Tags.TagID != value)
                        {
                            Tags = null;
                        }
                    }
                    _tagID = value;
                    OnPropertyChanged("TagID");
                }
            }
        }
        private Nullable<int> _tagID;
    
        [DataMember]
        public Nullable<int> ProductID
        {
            get { return _productID; }
            set
            {
                if (_productID != value)
                {
                    ChangeTracker.RecordOriginalValue("ProductID", _productID);
                    if (!IsDeserializing)
                    {
                        if (Templates != null && Templates.ProductID != value)
                        {
                            Templates = null;
                        }
                    }
                    _productID = value;
                    OnPropertyChanged("ProductID");
                }
            }
        }
        private Nullable<int> _productID;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Tags Tags
        {
            get { return _tags; }
            set
            {
                if (!ReferenceEquals(_tags, value))
                {
                    var previousValue = _tags;
                    _tags = value;
                    FixupTags(previousValue);
                    OnNavigationPropertyChanged("Tags");
                }
            }
        }
        private Tags _tags;
    
        [DataMember]
        public Templates Templates
        {
            get { return _templates; }
            set
            {
                if (!ReferenceEquals(_templates, value))
                {
                    var previousValue = _templates;
                    _templates = value;
                    FixupTemplates(previousValue);
                    OnNavigationPropertyChanged("Templates");
                }
            }
        }
        private Templates _templates;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Tags = null;
            Templates = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupTags(Tags previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TemplateThemeTags.Contains(this))
            {
                previousValue.TemplateThemeTags.Remove(this);
            }
    
            if (Tags != null)
            {
                if (!Tags.TemplateThemeTags.Contains(this))
                {
                    Tags.TemplateThemeTags.Add(this);
                }
    
                TagID = Tags.TagID;
            }
            else if (!skipKeys)
            {
                TagID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Tags")
                    && (ChangeTracker.OriginalValues["Tags"] == Tags))
                {
                    ChangeTracker.OriginalValues.Remove("Tags");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Tags", previousValue);
                }
                if (Tags != null && !Tags.ChangeTracker.ChangeTrackingEnabled)
                {
                    Tags.StartTracking();
                }
            }
        }
    
        private void FixupTemplates(Templates previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TemplateThemeTags.Contains(this))
            {
                previousValue.TemplateThemeTags.Remove(this);
            }
    
            if (Templates != null)
            {
                if (!Templates.TemplateThemeTags.Contains(this))
                {
                    Templates.TemplateThemeTags.Add(this);
                }
    
                ProductID = Templates.ProductID;
            }
            else if (!skipKeys)
            {
                ProductID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Templates")
                    && (ChangeTracker.OriginalValues["Templates"] == Templates))
                {
                    ChangeTracker.OriginalValues.Remove("Templates");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Templates", previousValue);
                }
                if (Templates != null && !Templates.ChangeTracker.ChangeTrackingEnabled)
                {
                    Templates.StartTracking();
                }
            }
        }

        #endregion
    }
}
